name: Clarification request
about: Not a bug, but something is not clear
title: "[QUESTION] "
labels: ["QUESTION"]
assignees: ["ageron"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve this project!

        Before you create this issue, please:

        * search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-mlp/issues?q=is%3Aissue
        * make sure you are using the latest updated code and libraries: https://github.com/ageron/handson-mlp/blob/main/INSTALL.md#update-this-project-and-its-libraries
        * read the FAQ: https://github.com/ageron/handson-mlp#faq
  - type: input
    id: chapter
    attributes:
      label: Enter the chapter number
      placeholder: Chapter
    validations:
      required: true
  - type: input
    id: page
    attributes:
      label: Enter the page number
      placeholder: Page number
  - type: input
    id: cell
    attributes:
      label: Enter the cell number
      placeholder: Cell number
  - type: dropdown
    id: environment
    attributes:
      label: Enter the environment you are using to run the notebook
      options:
        - Colab
        - Kaggle
        - Jupyter on Windows
        - Jupyter on Linux
        - Jupyter on MacOS
        - Other (specify in description)
  - type: markdown
    attributes:
      value: |
        Please ask your question below. If you want to include some code, please use code blocks like this:

        \`\`\`python
        def inverse(x):
            return 1 / x

        result = inverse(0)
        \`\`\`
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: It's unclear why...
    validations:
      required: true
