version: "3"
services:
  handson-ml3:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile #Dockerfile.gpu
      args:
        - username=devel
        - userid=1000
    container_name: handson-mlp
    image: ageron/handson-mlp:latest #latest-gpu
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/home/devel/handson-mlp
    command: /opt/conda/envs/homlp/bin/jupyter lab --ip='0.0.0.0' --port=8888 --no-browser
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - capabilities: [gpu]
